# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/alpine319"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "abosselS" do |server|
    server.vm.hostname = "abosselS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/vagrant"
    server.vm.provider "virtualbox" do |v|
      v.name = "abosselS"
    end
    server.vm.provision :shell, inline: <<-SHELL
      echo Start k3s...
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface eth1 --write-kubeconfig-mode=644" sh -

      echo Wait for k3s token...
      while [ ! -f /var/lib/rancher/k3s/server/node-token ]; do sleep 1; done; sleep 1

      echo Wait for 5 seconds...
      sleep 5

      kubectl apply -f /vagrant/conf/app1-configmap.yaml
      kubectl apply -f /vagrant/conf/app2-configmap.yaml
      kubectl apply -f /vagrant/conf/app3-configmap.yaml

      kubectl apply -f /vagrant/conf/app1-deployment.yaml
      kubectl apply -f /vagrant/conf/app2-deployment.yaml
      kubectl apply -f /vagrant/conf/app3-deployment.yaml

      kubectl apply -f /vagrant/conf/app1-service.yaml
      kubectl apply -f /vagrant/conf/app2-service.yaml
      kubectl apply -f /vagrant/conf/app3-service.yaml

      kubectl apply -f /vagrant/conf/ingress.yaml

      echo "alias k='k3s kubectl'" >> /home/vagrant/.bashrc >> /home/vagrant/.bash_profile
    SHELL
  end
end
