apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>App 2</title>
      </head>
      <body>
        <h1>Welcome to App 2</h1>
      </body>
    </html>
