apiVersion: v1
kind: ConfigMap
metadata:
  name: app-three-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>App 3</title>
      </head>
      <body>
        <h1>Welcome to App 3</h1>
      </body>
    </html>
